# E-commerce Exploratory Data Analysis  <a class="anchor"  id="title"></a>

For this project, the main focus will be on performing Exploratory Data Analysis (EDA) from various angles, including customer demographics, products, sales timeline, etc.

In [1]:
# intall python packages
import numpy as np # linear algebra
import pandas as pd # data processing
import plotly.express as px # create interactive charts

In [2]:
# read file
df = pd.read_csv("/kaggle/input/e-commerce-customer-for-behavior-analysis/ecommerce_customer_data_large.csv")

df.info() # get info about count and datatypes
df.shape  # returns a tuple of total # of rows and columns
df.head() # preview first 4 rows of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202618 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

In [3]:
# count distinct values in each column
df.nunique()

Customer ID               49661
Purchase Date            249728
Product Category              4
Product Price               491
Quantity                      5
Total Purchase Amount      5245
Payment Method                3
Customer Age                 53
Returns                       2
Customer Name             39878
Age                          53
Gender                        2
Churn                         2
dtype: int64

In [4]:
# check duplicates, returns all duplicated rows 
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Customer ID, Purchase Date, Product Category, Product Price, Quantity, Total Purchase Amount, Payment Method, Customer Age, Returns, Customer Name, Age, Gender, Churn]
Index: []

In [5]:
# Replace all NaN to 0 for Returns
# Convert dtype to integer
df['Returns'] = df['Returns'].fillna(0).astype(int)

#check non-null count & dtype
df['Returns'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 250000 entries, 0 to 249999
Series name: Returns
Non-Null Count   Dtype
--------------   -----
250000 non-null  int64
dtypes: int64(1)
memory usage: 1.9 MB

In [6]:
# Convert `Purchase Date` dtype to Datetime
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])

# Split Year and Month into new columns
df['Purchase Year'] = df['Purchase Date'].dt.year
df['Purchase Month'] = df['Purchase Date'].dt.month_name()

df[['Purchase Date','Purchase Year','Purchase Month']]

             Purchase Date  Purchase Year Purchase Month
0      2023-05-03 21:30:02           2023            May
1      2021-05-16 13:57:44           2021            May
2      2020-07-13 06:16:57           2020           July
3      2023-01-17 13:14:36           2023        January
4      2021-05-01 11:29:27           2021            May
...                    ...            ...            ...
249995 2023-01-24 12:32:18           2023        January
249996 2021-06-04 05:45:25           2021           June
249997 2022-11-10 17:11:57           2022       November
249998 2021-06-27 14:42:12           2021           June
249999 2020-09-07 05:12:19           2020      September

[250000 rows x 3 columns]

In [7]:
# Re-calculate total purchase amount
# Remove incorrect `Total Purchased Amount` column
df['Total Price'] = df['Product Price'] * df['Quantity']
#df = df.drop(['Total Purchase Amount'], axis=1)

# Re-order columns & exclude `Total Purchased Amount` and `Age`
cols = ['Customer ID','Customer Name','Purchase Date','Purchase Year','Purchase Month','Product Category','Product Price','Quantity','Total Price','Payment Method','Returns','Gender','Customer Age','Churn']
df = df[cols]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Customer ID       250000 non-null  int64
 1   Customer Name     250000 non-null  object
 2   Purchase Date     250000 non-null  datetime64[ns]
 3   Purchase Year     250000 non-null  int32
 4   Purchase Month    250000 non-null  object
 5   Product Category  250000 non-null  object
 6   Product Price     250000 non-null  int64
 7   Quantity          250000 non-null  int64
 8   Total Price       250000 non-null  int64
 9   Payment Method    250000 non-null  object
 10  Returns           250000 non-null  int64
 11  Gender            250000 non-null  object
 12  Customer Age      250000 non-null  int64
 13  Churn             250000 non-null  int64
dtypes: datetime64[ns](1), int32(1), int64(7), object(5)
memory usage: 25.7+ MB

In [8]:
# Save cleaned dataset to a csv file or copy to a new dataframe
df_2 = df.copy()
#df.to_csv('ecommerce_data_cleaned.csv', index=False)

### Data Exploration & Visualization (ANALYZE & SHARE)

### **4.1 Basic data summary & stats**

In [9]:
# Get an overall stats of the data
df_2.describe(include='all')

,Customer ID,Customer Name,Purchase Date,Purchase Year,Purchase Month,Product Category,Product Price,Quantity,Total Price,Payment Method,Returns,Gender,Customer Age,Churn
count,250000.000000,250000,250000,250000.000000,250000,250000,250000.000000,250000.000000,250000.000000,250000,250000.000000,250000,250000.000000,250000.00000
unique,NaN,39878,NaN,NaN,12,4,NaN,NaN,NaN,3,NaN,2,NaN,NaN
top,NaN,Michael Johnson,NaN,NaN,August,Electronics,NaN,NaN,NaN,Credit Card,NaN,Male,NaN,NaN
freq,NaN,119,NaN,NaN,23160,62630,NaN,NaN,NaN,83547,NaN,125676,NaN,NaN
mean,25017.632092,NaN,2021-11-06 19:26:22.286192384,2021.377136,NaN,NaN,254.742724,3.004936,765.954660,NaN,0.405904,NaN,43.798276,0.20052
min,1.000000,NaN,2020-01-01 00:07:26,2020.000000,NaN,NaN,10.000000,1.000000,10.000000,NaN,0.000000,NaN,18.000000,0.00000
25%,12590.000000,NaN,2020-12-03 08:10:12,2020.000000,NaN,NaN,132.000000,2.000000,288.000000,NaN,0.000000,NaN,30.000000,0.00000
50%,25011.000000,NaN,2021-11-06 07:39:08.500000,2021.000000,NaN,NaN,255.000000,3.000000,604.000000,NaN,0.000000,NaN,44.000000,0.00000
75%,37441.250000,NaN,2022-10-11 01:21:56.249999872,2022.000000,NaN,NaN,377.000000,4.000000,1135.000000,NaN,1.000000,NaN,57.000000,0.00000
max,50000.000000,NaN,2023-09-13 18:42:49,2023.000000,NaN,NaN,500.000000,5.000000,2500.000000,NaN,1.000000,NaN,70.000000,1.00000
std,14412.515718,NaN,NaN,1.074712,NaN,NaN,141.738104,1.414737,593.494204,NaN,0.491067,NaN,15.364915,0.40039

In [10]:
# Summarize object variables
df_2.describe(include=['object'])

          Customer Name Purchase Month Product Category Payment Method  Gender
count            250000         250000           250000         250000  250000
unique            39878             12                4              3       2
top     Michael Johnson         August      Electronics    Credit Card    Male
freq                119          23160            62630          83547  125676

In [11]:
df_2.head()

,Customer ID,Customer Name,Purchase Date,Purchase Year,Purchase Month,Product Category,Product Price,Quantity,Total Price,Payment Method,Returns,Gender,Customer Age,Churn
0,44605,John Rivera,2023-05-03 21:30:02,2023,May,Home,177,1,177,PayPal,1,Female,31,0
1,44605,John Rivera,2021-05-16 13:57:44,2021,May,Electronics,174,3,522,PayPal,1,Female,31,0
2,44605,John Rivera,2020-07-13 06:16:57,2020,July,Books,413,1,413,Credit Card,1,Female,31,0
3,44605,John Rivera,2023-01-17 13:14:36,2023,January,Electronics,396,3,1188,Cash,0,Female,31,0
4,44605,John Rivera,2021-05-01 11:29:27,2021,May,Books,259,4,1036,PayPal,1,Female,31,0

In [12]:
# Overview stats of Gender and total price spent
gender_summary = df_2.groupby('Gender').agg(total_count=('Customer ID','size'),
                                            min_amount=('Total Price', 'min'),
                                            max_amount=('Total Price', 'max'),
                                            median_amount=('Total Price','median'),
                                            total_amount=('Total Price','sum'),
                                            average_amount =('Total Price','mean'),
                                            total_returned=('Returns','sum'),
                                            return_rates=('Returns','mean'),
                                            total_churned=('Churn','sum'),
                                            churn_rates=('Churn','mean')).reset_index()

gender_summary

,Gender,total_count,min_amount,max_amount,median_amount,total_amount,average_amount,total_returned,return_rates,total_churned,churn_rates
0,Female,124324,10,2500,605.0,95363311,767.054720,50284,0.404459,25067,0.201626
1,Male,125676,10,2500,604.0,96125354,764.866434,51192,0.407333,25063,0.199426

In [13]:
## 1. Gender distribution 
# calculate count for each gender
gender_count = df_2['Gender'].value_counts()
# create pie chart
fig1 = px.pie(values=gender_count, names=gender_count.index,
              color = gender_count.index,
              color_discrete_map={'Female':'#FF6692', 'Male':'#3366CC'},
              title='1. Gender Distribution')
# adjust in-graph text
fig1.update_traces(textposition='inside', textinfo='text', 
                   texttemplate='%{label}<br>%{value}<br>(%{percent})')
# adjust chart size and remove legend
fig1.update_layout(title={'x': 0.5, 'y': 0.9},
                   width=400, height=400, showlegend=False)


## 2 Average price spent breakdown by year
# Calculate the overall average spending and prepare data for plotting
overall_avg_price = df_2['Total Price'].mean()
avg_price_gender_year = df_2.groupby(['Gender', 'Purchase Year'], as_index=False)['Total Price'].mean()

# Create box plot visualizing total price by gender and year, including overall average line
fig2 = px.box(df_2, x='Gender', y='Total Price', color='Purchase Year',
              title='2. Total Price Spent by Gender, Breakdown by Year',
              labels={'Total Price': 'Total Purchased Amount ($)'})

fig2.add_hline(y=overall_avg_price, line_dash="dash", line_color="#325A9B",
               annotation_text=f'Overall Average: ${overall_avg_price:.2f}',
               annotation_position="top",  # Adjusted for better visibility
               annotation_font_color="#325A9B")

fig2.update_layout(title={'x': 0.5, 'y': 0.9}, 
                   width=700, height=450,
                   xaxis_title=None)

# display graphs
fig1.show()
fig2.show()

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [14]:
# Define bins for age groups
age_bins = [0,9,19,29,39,49,59,69,np.inf]
age_labels = ['0-9','10-19','20-29','30-39','40-49','50-59','60-69','70+']

# Add a new column and assign age group category to each transaction in df_2
df_2['Age Group'] = pd.cut(df_2['Customer Age'], bins=age_bins, labels=age_labels) 

# Check if `Age Group` is assigned correctly and added to the dataset
df_2[['Customer ID','Customer Age','Age Group']].sort_values('Customer Age', ascending=False)

#df_2[df_2['Age Group'].isnull()] # check any missing values

        Customer ID  Customer Age Age Group
213450        27866            70       70+
76898         27353            70       70+
76896         27353            70       70+
76895         27353            70       70+
239854         5761            70       70+
...             ...           ...       ...
157044        44571            18     10-19
83330         12369            18     10-19
93626          8277            18     10-19
93625          8277            18     10-19
190060        45939            18     10-19

[250000 rows x 3 columns]

In [15]:
## 1. Age distribution by age
# Ensure the 'Age Group' in df_2 is categorized according to age_labels
# this will help to connect the data points in the correct order in line chart
df_2['Age Group'] = pd.Categorical(df_2['Age Group'], categories=age_labels, ordered=True)

# Count each age group
age_group_count = df_2['Age Group'].value_counts().sort_index().reset_index(name='Count')

# Calculate the percentage for each age group
age_group_count['Percentage'] = round(age_group_count['Count'] / age_group_count['Count'].sum()*100, 2)
age_group_count['Percentage Text'] = age_group_count['Percentage'].astype(str) + '%'

# Plot a line chart with bars
fig1 = px.line(age_group_count,x='Age Group', y='Count',
               title='1. Age Distribution',
               markers=True,
               text='Percentage Text',
               labels={'Count': 'Number of Customers'})

fig1.update_traces(textposition="top center") #adjust text position for percentages 
fig1.add_bar(x=age_group_count['Age Group'], y=age_group_count['Count'], text=age_group_count['Count'], textposition='inside', name='Count')
fig1.update_traces(textfont_color='white', selector=dict(type='bar'))
fig1.update_layout(title={'x': 0.5, 'y': 0.9},
                   xaxis_title= None,
                   yaxis_title= 'Count',
                   width=750, height=450, 
                   showlegend=False)


## 2. Age distrbution by gender
# count each age group by gender
age_group_gender_count = df_2[['Gender','Age Group']].value_counts().reset_index(name='Count')

fig2 = px.bar(age_group_gender_count, x='Age Group', y='Count', 
              color='Gender', barmode='group', 
              color_discrete_map={'Female': '#FF6692', 'Male': '#3366CC'},
              category_orders={'Age Group': age_labels},
              title='2. Age Distribution by Gender',
              text_auto=True)
fig2.update_layout(title={'x': 0.5, 'y': 0.9},
                   width=750, height=450,
                   xaxis_title= None,
                   legend_title=None,
                   legend=dict(orientation="h",yanchor="bottom",
                               y=1.02, xanchor="center",x=0.5))


## 3. Average price spent by age group
# calculate overall and average of total spending for each age group
overall_avg_price = df_2['Total Price'].mean()
avg_price_age_group = df_2.groupby(['Age Group'])['Total Price'].mean().reset_index(name='Avg Price')

fig3 = px.bar(avg_price_age_group, x= 'Age Group', y= 'Avg Price', 
              color = 'Avg Price',
              color_continuous_scale= "peach", 
              category_orders={'Age Group': age_labels},
              title='3. Average Price Spent by Age Group',
              text= [f"${value:.2f}" for value in avg_price_age_group['Avg Price']],
              hover_data={'Age Group':True, 'Avg Price':"${:.2f}"})

# Adjust data and format shown in the hover data
fig3.update_traces(hovertemplate="Age Group: %{x}<br>"
                                 "Average Spending: %{y:$,.2f}")

# Add a line to show the overall average for spending 
fig3.add_hline(y=overall_avg_price, line_dash="dash", line_color="#1CBE4F",
               annotation_text=f'Overall Average: ${overall_avg_price:.2f}',
               annotation_font_color="#1CBE4F",
               annotation_position="top left")

fig3.update_layout(title={'x': 0.5, 'y': 0.9},
                   width=700, height=450,
                   xaxis_title= None, 
                   yaxis_title= 'Average Spending ($)',
                   yaxis=dict(range=[500, 800],  # Set range from 400 to 800
                              tick0=500,  # Set starting tick at 400
                              dtick=50),  # Set interval between ticks
                   showlegend=False)


# display graphs
fig1.show()
fig2.show()
fig3.show()

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/tmp/ipykernel_18/1762810529.py:51: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [16]:
# To include stats abour product reutrns, 
# we'll need to calculate the Return_Quantity when Returns == 1  
# (assuming all items are returned altogether for each transaction)
df_2['Return Quantity'] = df_2.apply(lambda row: row['Quantity'] if row['Returns'] == 1 else 0, axis=1)

product_summary_table = df_2.groupby('Product Category').agg(Count=('Product Category', 'size'),
                                               Order_Quantity=('Quantity', 'sum'),
                                               Total_Revenue=('Total Price','sum'),
                                               Average_Revenue=('Total Price','mean'),
                                               Return_Count=('Return Quantity', 'sum')).reset_index()
product_summary_table

,Product Category,Count,Order_Quantity,Total_Revenue,Average_Revenue,Return_Count
0,Books,62247,186608,47578138,764.344274,76551
1,Clothing,62581,188688,47977746,766.650357,76279
2,Electronics,62630,187861,47801925,763.243254,76278
3,Home,62542,188077,48130856,769.576541,76336

In [17]:
# 1. Product Distribution by category
# Calculate the overall percentage for product quantity sold
total_order_quantity = product_summary_table['Order_Quantity'].sum()
product_summary_table['Overall_Percentage'] = (product_summary_table['Order_Quantity'] / total_order_quantity) * 100

# Calculate the percentage for return
product_summary_table['Return_Rate'] = round((product_summary_table['Return_Count'] / product_summary_table['Order_Quantity']) * 100, 2)

product_summary_table

,Product Category,Count,Order_Quantity,Total_Revenue,Average_Revenue,Return_Count,Overall_Percentage,Return_Rate
0,Books,62247,186608,47578138,764.344274,76551,24.840196,41.02
1,Clothing,62581,188688,47977746,766.650357,76279,25.117074,40.43
2,Electronics,62630,187861,47801925,763.243254,76278,25.006989,40.60
3,Home,62542,188077,48130856,769.576541,76336,25.035741,40.59

In [18]:
# 1. Product Distribution and Returns by category
# Set the category order for plotting colors
category_order = ["Electronics", "Clothing", "Home", "Books"]

fig1 = px.bar(product_summary_table, 
             x='Product Category', 
             y=['Order_Quantity', 'Return_Count'],
             barmode='overlay', opacity=0.7,
             color='Product Category',
             color_discrete_sequence=px.colors.qualitative.T10,
             pattern_shape = 'variable',
             category_orders={'Product Category': category_order},
             title='Product Category Distribution vs. Returns',
             labels={'value': 'Return & Total Order Count'})

# Add overall percentage and returns rate as text on the graph
for i, row in product_summary_table.iterrows():
    fig1.add_annotation(x=row['Product Category'], y=row['Order_Quantity']-15000, text=f"Total:{row['Order_Quantity']/ 1000:,.2f}K<br>({row['Overall_Percentage']:.2f}%)",
                       font=dict(color='black', size=12), showarrow=False)

for i, row in product_summary_table.iterrows():
    fig1.add_annotation(x=row['Product Category'], y=row['Return_Count']-15000, text=f"Returned:{row['Return_Count']/ 1000:,.2f}K<br>({row['Return_Rate']:.2f}%)",
                       font=dict(color='white', size=12), showarrow=False)
    

fig1.update_layout(title={'x': 0.5, 'y': 0.9},
                  xaxis_title= None,
                  width=700, height=500,
                  showlegend=False)



# 2. Sales Revenue by Product Category
total_revenue = df_2.groupby(['Product Category','Purchase Year'])['Total Price'].sum().reset_index()
total_revenue['Purchase Year'] = total_revenue['Purchase Year'].astype(str)

fig2 = px.bar(total_revenue, x='Product Category', y='Total Price',
              color='Purchase Year', barmode= 'group',
              color_discrete_sequence=px.colors.qualitative.Set2,
              category_orders={'Product Category': category_order},
              title = '2. Sales Revenue by Product Category and Year',
              labels={'Total Price': 'Total Price ($)'})
fig2.update_traces(texttemplate='%{y:$.4s}', textposition='inside', textangle=90)
fig2.update_layout(title={'x': 0.5, 'y': 0.9},
                  xaxis_title= None,
                  width=700, height=500)


# 3. Product revenue by Gender
product_revenue_gender = df_2.groupby(['Product Category','Gender'])['Total Price'].sum().reset_index(name='Total Revenue')

fig3 = px.bar(product_revenue_gender,x='Product Category', y='Total Revenue', 
              color='Gender',
              color_discrete_map={'Female': '#FF6692', 'Male': '#3366CC'},
              barmode='group', 
              title='3. Sales Revenue by Product Category & Gender',
              category_orders={'Product Category': category_order},
              labels={'Total Revenue': 'Total Revenue ($)'})

fig3.update_traces(texttemplate='%{y:$.4s}', textposition='inside', textangle=90)

fig3.update_layout(title={'x': 0.5, 'y': 0.9},
                  xaxis_title= None,
                  width=700, height=500,
                  legend_title=None,
                  legend=dict(orientation="h",yanchor="bottom",
                              y=1.02, xanchor="center",x=0.5))


# 4. Product revenue by Age Group
product_revenue_age = df_2.groupby(['Product Category','Age Group'])['Total Price'].sum().reset_index(name='Total Revenue')

fig4 = px.bar(product_revenue_age[product_revenue_age['Total Revenue'] > 0], #filter out empty bars
              x='Age Group', y='Total Revenue',
              color='Product Category', barmode= 'group',
              color_discrete_sequence=px.colors.qualitative.T10,
              category_orders={'Product Category': category_order},
              title = '4. Product Sales Revenue by Category & Age Group',
              labels={'Total Revenue': 'Total Revenue ($)'})

fig4.update_traces(texttemplate='%{y:$.3s}', textangle=90)

fig4.update_layout(title={'x': 0.5, 'y': 0.9},
                  xaxis_title= None,
                  width=800, height=500,
                  legend_title=None,
                  legend=dict(orientation="h",yanchor="bottom",
                              y=1.02, xanchor="center",x=0.5))


fig1.show()
fig2.show()
fig3.show()
fig4.show()

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

/tmp/ipykernel_18/1380884117.py:71: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/opt/conda/lib/python3.10/site-packages/plotly/express/_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [19]:
# Quick overview of yearly sales revenue
annual_sales_summary = df_2.groupby('Purchase Year')['Total Price'].agg(['min', 'max','mean','median','sum',])
annual_sales_summary

               min   max        mean  median       sum
Purchase Year
2020            10  2500  766.229627   604.0  51931213
2021            10  2500  765.467205   608.0  51594786
2022            10  2500  766.071850   600.0  51774966
2023            10  2500  766.088024   604.0  36187700

In [20]:
# Set month names in order and dtype to category
month_order = ['January', 'February', 'March', 'April', 'May', 'June', 
               'July', 'August', 'September', 'October', 'November', 'December']

df_2['Purchase Month'] = pd.Categorical(df_2['Purchase Month'], 
                                        categories=month_order, 
                                        ordered=True)

# Calculate the total and average of monthly sales revenue
monthly_sales = df_2.groupby(['Purchase Year', 'Purchase Month']).agg(Count=('Customer ID', 'size'),
                                                                      Total_Revenue=('Total Price', 'sum'),
                                                                      Avg_Revenue=('Total Price', 'mean')).reset_index()

/tmp/ipykernel_18/2149485385.py:10: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [21]:
## 1. Monthly count of orders, split by years
# Convert years to string for bar chart
monthly_sales['Purchase Year'] = monthly_sales['Purchase Year'].astype(str)

fig1 = px.bar(monthly_sales, x='Purchase Month', y='Count', 
               color='Purchase Year', facet_row='Purchase Year',
               title='1. Number of Orders per Month (by Year)', 
               labels={'Count': 'Order Count', 'Purchase Year': 'Year'},
               hover_data={'Count': ':,.0f'},
               text_auto=True)

fig1.update_layout(title={'x': 0.5, 'y': 0.9},
                  xaxis_title= None, 
                  width=650, height=600,
                  showlegend=False)

## 2. Compare total monthly sales
# Filter out data points where 'Total_Revenue' is 0
fig2 = px.area(monthly_sales[monthly_sales['Total_Revenue'] != 0], x='Purchase Month', y='Total_Revenue', 
              color='Purchase Year', facet_col='Purchase Year',
              color_discrete_sequence=px.colors.qualitative.Dark2,
              title='2. Total Monthly Sales Revenue (by Year)',
              labels={'Total_Revenue': 'Total Revenue ($)', 'Purchase Year': 'Year'},
              hover_data={'Total_Revenue': ':$,.0f'},
              markers=True)

fig2.update_yaxes(tickprefix="$")

fig2.update_layout(title={'x': 0.5, 'y': 0.9},
                  xaxis_title= None,
                  xaxis2_title= None,
                  xaxis3_title= None,
                  xaxis4_title= None,
                  width=800, height=350,
                  showlegend=False)

## 3. Compare average monthly sales
fig3 = px.line(monthly_sales, x='Purchase Month', y='Avg_Revenue', 
              color='Purchase Year', facet_col='Purchase Year',
              color_discrete_sequence=px.colors.qualitative.Set2,
              title='3. Average Monthly Sales Revenue (by Year)',
              labels={'Avg_Revenue': 'Average Revenue ($)', 'Purchase Year': 'Year'},
              hover_data={'Avg_Revenue': ':$,.0f'},
              markers=True)

fig3.update_yaxes(tickprefix="$")

fig3.update_layout(title={'x': 0.5, 'y': 0.9},
                  xaxis_title= None,
                  xaxis2_title= None,
                  xaxis3_title= None,
                  xaxis4_title= None,
                  width=800, height=350,
                  yaxis=dict(range=[700, 840]), 
                  showlegend=False)


                 
#display all charts
fig1.show()
fig2.show()
fig3.show()